{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "axonhub.postgresql.serviceName" . }}
  labels:
    {{- include "axonhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "axonhub.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}